name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y libboost-atomic-dev
      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build --parallel 8
      - name: Test
        run: |
          build/lglfileconvert2d tests/simple.ncol simple.lgl
          build/lglayout2d simple.lgl
          # cmp lgl.out tests/simple.out
          # cmp lgl.out.root tests/simple.out.root

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-docker-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
